<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Providers} from "./providers";
import "./globals.css";


import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Therapute",
  description: "Generated by Therapute",
};
=======
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
>>>>>>> e0b1892f3b3088d5d929bebf3e094df282dae262

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
